// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzpApUm76Z7DOvZEPJZJDpn9JTDLV9eTQ',
    appId: '1:584046048279:web:69a2e622b2f862ff479852',
    messagingSenderId: '584046048279',
    projectId: 'umm-erm-hmm',
    authDomain: 'umm-erm-hmm.firebaseapp.com',
    storageBucket: 'umm-erm-hmm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHucASlB22Y10O0nzdHY6ZADwuwbNV10',
    appId: '1:584046048279:android:cd712a68cbb87add479852',
    messagingSenderId: '584046048279',
    projectId: 'umm-erm-hmm',
    storageBucket: 'umm-erm-hmm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Rwi9myRALp3LzUiFEe9-GfXetevxfjo',
    appId: '1:584046048279:ios:49f471a13ac85a11479852',
    messagingSenderId: '584046048279',
    projectId: 'umm-erm-hmm',
    storageBucket: 'umm-erm-hmm.appspot.com',
    iosBundleId: 'com.haani.dressbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Rwi9myRALp3LzUiFEe9-GfXetevxfjo',
    appId: '1:584046048279:ios:49f471a13ac85a11479852',
    messagingSenderId: '584046048279',
    projectId: 'umm-erm-hmm',
    storageBucket: 'umm-erm-hmm.appspot.com',
    iosBundleId: 'com.haani.dressbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzpApUm76Z7DOvZEPJZJDpn9JTDLV9eTQ',
    appId: '1:584046048279:web:8f2ad18766a1abcc479852',
    messagingSenderId: '584046048279',
    projectId: 'umm-erm-hmm',
    authDomain: 'umm-erm-hmm.firebaseapp.com',
    storageBucket: 'umm-erm-hmm.appspot.com',
  );
}
